### ISSUE TITLE
event handlers / listeners

### ISSUE THREAD

**Issue by deblasis** [reactjs/it.reactjs.org#10]
This is to discuss how do we want to "handle the handlers" 🤣 

Jokes apart, we need to define a way to translate consistently
- event handler
- event listener

I'd personally keep them in English. We are not teaching CS, or either English, we are teaching React! 
I'll have a look at how the other languages groups are dealing with these instances, just to be aligned

**Comment by LucaBlackDragon** [comment]
Maybe we could add an explanation the first time we mention those expression, i.e.:
> You can attach an event listener to the...
>
> Puoi assegnare un *event handler* (una funzione invocata quando viene emesso un evento) al...

**Comment by deblasis** [comment]
Totally agree

**Comment by frankcalise** [comment]
So if I'm translating a page in the advanced area, should I assume this has already been covered? Or should I use the definition in parenthesis the first time event handler appears on my page?
