### ISSUE TITLE
Translation of the "React" name

### ISSUE THREAD

**Issue by GCrispino** [reactjs/it.reactjs.org#106]
How should we translate the React name itself? In the Portuguese translation, for example, we've used "o React", which would be something like "il React", in Italian. Should we use this or only "React" would do the job?

**Comment by LucaBlackDragon** [comment]
In already translated articles we are generally sticking with "React" (without preceding article)

**Comment by GCrispino** [comment]
Cool. I'm gonna leave it like that then. Thanks!

**Comment by Fs00** [comment]
Agree, a preceding article would just sound redundant.

**Comment by LucaBlackDragon** [comment]
@deblasis what do you think? Should we close this issue? Do you think it's useful to add its contents to the Glossary?

**Comment by deblasis** [comment]
Yeah I believe it can be safely closed, I have never heard anyone referring to React with the article either in English or in Italian.
