### ISSUE TITLE
Translating "mount" and "unmount" in sentences

### ISSUE THREAD

**Issue by LucaBlackDragon** [reactjs/it.reactjs.org#108]
Whenever "mount" and "unmount" are used as keywords, I think we should leave those terms unchanged.
But is it OK to translate "mount" and "unmount" with "montare" and "smontare" when those terms are used as verbs in a sentence?

E.g.

```
We can declare special methods on the component class to run some code when a component mounts and unmounts
```

would become:

```
Possiamo dichiarare alcuni metodi speciali nel componente classe per eseguire del codice quando il componente viene montato e smontato
```

**Comment by deblasis** [comment]
I agree with you, not translated when keywords but translated otherwise. 👍
