### ISSUE TITLE
Failure to sync with master with bot due to protected branch

### ISSUE THREAD

**Issue by tesseralis** [reactjs/it.reactjs.org#115]
I tried running the sync bot but it's failing because the master branch is protected.

```
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Required status check "ci/circleci: build" is expected. At least 1 approving review is required by reviewers with write access.
To https://github.com/reactjs/it.reactjs.org.git
 ! [remote rejected]   master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/reactjs/it.reactjs.org.git'
```

The bot automatically commits if it doesn't detect any conflicts -- no conflicts usually mean the changes are code-related or in a page that isn't translated yet.

I'm okay with writing some logic to get around this, but I was just wondering if you all would be okay with dropping the restrictions. For example, the main reactjs.org repo doesn't even have it:

<img width="1084" alt="screen shot 2019-02-27 at 2 31 43 pm" src="https://user-images.githubusercontent.com/1278991/53527694-85772d00-3a9c-11e9-8464-6c97a8abc969.png">

**Comment by deblasis** [comment]
Hi @tesseralis! I have seen the same branch protection in some other translation project few days ago, however, I just removed it.

**Comment by deblasis** [comment]
I have approved #116 but not merged it yet (no conflicts). Up to you if you wanna do that or abandon it and try again with the bot now that the condition above has been removed.

**Comment by deblasis** [comment]
Closing the issue since #116 was merged
