### ISSUE TITLE
Pooling / Pooled term

### ISSUE THREAD

**Issue by frankcalise** [reactjs/it.reactjs.org#126]
Is there a good term for pooling or pooled? I'm not seeing something that stands out and makes sense to me exactly. Or could not translate it since it defines it afterwards:

> Event Pooling
>  The `SyntheticEvent` is pooled. This means that the `SyntheticEvent` object will be reused and all properties will be nullified after the event callback has been invoked.
This is for performance reasons.

Thoughts?

**Comment by frankcalise** [comment]
I guess "grouping" should get the point across. Sound ok?

Raggruppamento Eventi
Il `SyntheticEvent` è raggruppato

**Comment by LucaBlackDragon** [comment]
Maybe "Il `SyntheticEvent` è gestito in un pool" (and then the explanation)

**Comment by deblasis** [comment]
Addressing this in code-review #31
