### ISSUE TITLE
Boilerplate term

### ISSUE THREAD

**Issue by guerrap** [reactjs/it.reactjs.org#128]
What could be the correct translation for boilerplate? I think it may be added to the untranslatable terms. For example:
> to reduce the boilerplate code

could be:
> per ridurre il boilerplate del codice.

and it sounds quite good, isn't it?
Otherwise, does anybody have any suggestion?

**Comment by luzzif** [comment]
I think "rumore" would be a pretty good solution.

> per ridurre il rumore nel codice

Or maybe, changing the sentence a bit:

> per aumentare la pulizia del codice

Same meaning, different ways of wording it.

**Comment by LucaBlackDragon** [comment]
> Or maybe, changing the sentence a bit:
> 
> > per aumentare la pulizia del codice

This one is much better in my opinion
