### ISSUE TITLE
Italian Translation Final Steps!

### ISSUE THREAD

**Issue by tesseralis** [reactjs/it.reactjs.org#135]
Congrats on almost finishing the Italian docs! There are just a couple more things we need to do before we can mark the core pages as complete!

* [x] Change the [DocSearch API key](https://github.com/reactjs/es.reactjs.org/blob/ed07fa53dc9ab7950e630900f7da3a7c821d63a6/src/components/LayoutHeader/DocSearch.js#L25). One of the maintainers needs to [sign up for DocSearch](https://community.algolia.com/docsearch/#join-docsearch-program)
* [x] Go over the pages of the site one last time to check for consistency

**Comment by tesseralis** [comment]
Everything looks good so far -- only thing is the nav menu isn't translated yet.

**Comment by deblasis** [comment]
Hi @tesseralis! 
Awesome! I am just waiting for the confirmation email from Algolia and then I'll PR the API key change.
Also, I'll be working on the Nav menu next

**Comment by deblasis** [comment]
Hi @tesseralis I think we are good to go now :)
