### ISSUE TITLE
Translation for the page 'Basics -> Lifting State Up'

### ISSUE THREAD

**Issue by deblasis** [reactjs/it.reactjs.org#24]
# Please help us translating this page in Italian!
  
  **Aiutaci a tradurre questa pagina in Italiano!**

  You can find all the details about how to help here: https://github.com/reactjs/it.reactjs.org/issues/1
  
  ## GRAZIE! :smile:

**Comment by deblasis** [comment]
Ciao @lssmn! How is it going? Any update on this? It's the last page left for us to translate in the `Basics` section and then we can ship! 😁

**Comment by lssmn** [comment]
Ciao! Sorry for the delay but the page was quite tricky to translate (plus I went on holidays 2 weeks and forgot to open a "work in progress" PR 😬). I'm going to finalise it today 👌

**Comment by lssmn** [comment]
Ciao @deblasis @LucaBlackDragon. I do not know if you noticed but this [PR](https://github.com/reactjs/it.reactjs.org/pull/139) has been opened for 4 days already. Did you have any chance to review it?

**Comment by deblasis** [comment]
Ciao Alessio, just reviewed :)
