### ISSUE TITLE
Translation for the page 'API Reference -> ReactDOM'

### ISSUE THREAD

**Issue by deblasis** [reactjs/it.reactjs.org#28]
# Please help us translating this page in Italian!
  
  **Aiutaci a tradurre questa pagina in Italiano!**

  You can find all the details about how to help here: https://github.com/reactjs/it.reactjs.org/issues/1
  
  ## GRAZIE! :smile:

**Comment by Manugal** [comment]
Ciao. I'd like to work on it.

**Comment by deblasis** [comment]
Hey @Manugal ! Awesome! 
Please read the info in #1 and if you have any question, just comment here.
Ciao!!
