### ISSUE TITLE
Glossary

### ISSUE THREAD

**Issue by LucaBlackDragon** [reactjs/it.reactjs.org#3]
# Glossary

Glossary of the translations of technical and React-specific terms.

## Untranslatable terms
- footer

## Problematic terms
- to render (#7)

**Comment by deblasis** [comment]
I would close this and I would open specific PRs against **GLOSSARY.md** for when we are in doubt about something, agreed?

**Comment by LucaBlackDragon** [comment]
Agreed!

**Comment by LucaBlackDragon** [comment]
Moved [here](https://github.com/reactjs/it.reactjs.org/blob/master/GLOSSARY.md)
