### ISSUE TITLE
Translation for the page 'API Reference -> SyntheticEvent'

### ISSUE THREAD

**Issue by deblasis** [reactjs/it.reactjs.org#31]
# Please help us translating this page in Italian!
  
  **Aiutaci a tradurre questa pagina in Italiano!**

  You can find all the details about how to help here: https://github.com/reactjs/it.reactjs.org/issues/1
  
  ## GRAZIE! :smile:

**Comment by deblasis** [comment]
@frankcalise is working on this

**Comment by deblasis** [comment]
Ciao @frankcalise! How are you getting on? Feel free to ask questions in here if you need help with anything 👍 
As far as I understand, #126 is addressed, right?

**Comment by frankcalise** [comment]
@deblasis Ciao, things going well. I had to leave town for some unexpected family stuff so it put it on hold for a few days. I'm almost done with my initial rough draft and then could use the help reviewing it.

I believe I tried to push my separate branch to remove so people could take a look but it said I lacked permissions.

**Comment by deblasis** [comment]
Ciao @frankcalise! It's normal that you can't create branches here, you have to fork the project and then issue your PR from there. 
Shout if you need help.

Happy to review whenever you are ready 😄
