### ISSUE TITLE
Translation for the page 'API Reference -> Test Renderer'

### ISSUE THREAD

**Issue by deblasis** [reactjs/it.reactjs.org#34]
# Please help us translating this page in Italian!
  
  **Aiutaci a tradurre questa pagina in Italiano!**

  You can find all the details about how to help here: https://github.com/reactjs/it.reactjs.org/issues/1
  
  ## GRAZIE! :smile:

**Comment by Manugal** [comment]
Can I work on this?

**Comment by deblasis** [comment]
Sure, all yours Emanuele!

**Comment by Manugal** [comment]
Ready for review #129
