### ISSUE TITLE
Translation for the page 'API Reference -> Glossary'

### ISSUE THREAD

**Issue by deblasis** [reactjs/it.reactjs.org#36]
# Please help us translating this page in Italian!
  
  **Aiutaci a tradurre questa pagina in Italiano!**

  You can find all the details about how to help here: https://github.com/reactjs/it.reactjs.org/issues/1
  
  ## GRAZIE! :smile:

**Comment by Manugal** [comment]
Ciao.

Can I work on it?

**Comment by deblasis** [comment]
Ciao!

Sure, all yours

**Comment by deblasis** [comment]
Closed in #138
