### ISSUE TITLE
Translation for the page 'Installation -> CDN Links'

### ISSUE THREAD

**Issue by deblasis** [reactjs/it.reactjs.org#42]
# Please help us translating this page in Italian!
  
  **Aiutaci a tradurre questa pagina in Italiano!**

  You can find all the details about how to help here: https://github.com/reactjs/it.reactjs.org/issues/1
  
  ## GRAZIE! :smile:

**Comment by Manugal** [comment]
Can I work on this one?

**Comment by deblasis** [comment]
Ciao! Sure. All yours

**Comment by Manugal** [comment]
Ready for review #147 .
