### ISSUE TITLE
Translation for the page 'Hooks -> Using the State Hook'

### ISSUE THREAD

**Issue by deblasis** [reactjs/it.reactjs.org#45]
# Please help us translating this page in Italian!
  
  **Aiutaci a tradurre questa pagina in Italiano!**

  You can find all the details about how to help here: https://github.com/reactjs/it.reactjs.org/issues/1
  
  ## GRAZIE! :smile:

**Comment by one89** [comment]
Ciao! Vorrei dare il mio contributo, posso occuparmi della traduzione di questa pagina?

**Comment by deblasis** [comment]
Ciao Francesco!

Assolutamente si, dai uno sguardo alle linee guida e non esitare a chiedere
se hai domande.

**Comment by LucaBlackDragon** [comment]
Closed by #157
