### ISSUE TITLE
Translation for the page 'Hooks -> Using the Effect Hook'

### ISSUE THREAD

**Issue by deblasis** [reactjs/it.reactjs.org#46]
# Please help us translating this page in Italian!
  
  **Aiutaci a tradurre questa pagina in Italiano!**

  You can find all the details about how to help here: https://github.com/reactjs/it.reactjs.org/issues/1
  
  ## GRAZIE! :smile:

**Comment by one89** [comment]
Hey,
just submitted my PR #212 

I'm open for any improvement :)
