### ISSUE TITLE
Translation for the page 'Hooks -> Rules of Hooks'

### ISSUE THREAD

**Issue by deblasis** [reactjs/it.reactjs.org#47]
# Please help us translating this page in Italian!
  
  **Aiutaci a tradurre questa pagina in Italiano!**

  You can find all the details about how to help here: https://github.com/reactjs/it.reactjs.org/issues/1
  
  ## GRAZIE! :smile:

**Comment by hawz** [comment]
Ciao! Mi sto occupando della traduzione di questa pagina e volevo chiedere: una volta pronta è meglio creare una PR semplice o una draft PR? Grazie!

**Comment by LucaBlackDragon** [comment]
Hi @hawz , PR is the way! Prego!
