### ISSUE TITLE
Translation for the page 'Warnings -> invalid-aria-prop'

### ISSUE THREAD

**Issue by deblasis** [reactjs/it.reactjs.org#52]
# Please help us translating this page in Italian!
  
  **Aiutaci a tradurre questa pagina in Italiano!**

  You can find all the details about how to help here: https://github.com/reactjs/it.reactjs.org/issues/1
  
  ## GRAZIE! :smile:

**Comment by mbellagamba** [comment]
Hi, can I work on this?

**Comment by deblasis** [comment]
Sure!
