### ISSUE TITLE
Translation of verb "to render"

### ISSUE THREAD

**Issue by LucaBlackDragon** [reactjs/it.reactjs.org#7]
How sould we translate the verb "to render"?
Possible options:
- renderizzare
- generare
- emettere
- ...?

**Comment by LucaBlackDragon** [comment]
#2

**Comment by deblasis** [comment]
Very good point, I reckon I used "visualizzare" somewhere as well. Better to be aligned.

I vote for **renderizzare**: https://www.garzantilinguistica.it/ricerca/?q=renderizzazione

**Comment by deblasis** [comment]
Please 👀 #8 as I have added two additional translations that I am not 100% sure about.

| from| to| 
|-|-|
| React component class | classe componente React | 
| React component type | tipo componente React | 

context: https://github.com/reactjs/it.reactjs.org/pull/6/commits/317440657a122443ee338055a7f4087ca86fa2af#diff-898ac844052327a271c2c4dcbf2e4c5eR156

**Comment by LucaBlackDragon** [comment]
I think that's fine; another way to translate would be:

| from | to |comment
|------|----|---------|
|React component class|classe **di** componente React|this doesn't sound good to me|
|React component type|tipo **di** componente React|this sounds good|

**Comment by LucaBlackDragon** [comment]
> 
> 
> Very good point, I reckon I used "visualizzare" somewhere as well. Better to be aligned.
> 
> I vote for **renderizzare**: https://www.garzantilinguistica.it/ricerca/?q=renderizzazione

Agreed

**Comment by deblasis** [comment]
Awesome

**Comment by deblasis** [comment]
> I think that's fine; another way to translate would be:
> 
> from	to	comment
> React component class	classe **di** componente React	this doesn't sound good to me
> React component type	tipo **di** componente React	this sounds good

Forgot to add that regarding this, I'd rather stick to the version without **di** since we are referring to the type or class otherwise it might sound like we are referring to an instance of it. I hope I explained myself well enough!

**Comment by lssmn** [comment]
> Please 👀 #8 as I have added two additional translations that I am not 100% sure about.
> 
> from	to
> React component class	classe componente React
> React component type	tipo componente React
> context: [3174406#diff-898ac844052327a271c2c4dcbf2e4c5eR156](https://github.com/reactjs/it.reactjs.org/commit/317440657a122443ee338055a7f4087ca86fa2af#diff-898ac844052327a271c2c4dcbf2e4c5eR156)

What about the literal translation _componente classe React_ where _classe_ becomes an adjective (_fatto a_, component _built in that way_)? It would also work for _componente funzione React_. Translating some terms and concepts is definitely quite tricky 😬

**Comment by LucaBlackDragon** [comment]
> 
> 
> > Please 👀 #8 as I have added two additional translations that I am not 100% sure about.
> > from	to
> > React component class	classe componente React
> > React component type	tipo componente React
> > context: [3174406#diff-898ac844052327a271c2c4dcbf2e4c5eR156](https://github.com/reactjs/it.reactjs.org/commit/317440657a122443ee338055a7f4087ca86fa2af#diff-898ac844052327a271c2c4dcbf2e4c5eR156)
> 
> What about _componente classe React_ where _classe_ becomes an adjective (_fatto a_, component _built in that way_)? It would also work for _componente funzione React_. Translating some terms and concepts is definitely quite tricky 😬

I don't know... in the English version "component" is the adjective and "class" or "type" is the subject, I don't know if swapping them is OK.
This expressions are tricky to translate indeed! :D
