### ISSUE TITLE
Translation for the page 'Advanced Guides -> Reconciliation'

### ISSUE THREAD

**Issue by deblasis** [reactjs/it.reactjs.org#71]
# Please help us translating this page in Italian!
  
  **Aiutaci a tradurre questa pagina in Italiano!**

  You can find all the details about how to help here: https://github.com/reactjs/it.reactjs.org/issues/1
  
  ## GRAZIE! :smile:

**Comment by deblasis** [comment]
@mattveraldi is working on this

**Comment by mattveraldi** [comment]
Mantengo questo commento per tenervi aggiornati sullo stato effettivo della issue.  
### Stato: in progress
## Paragrafi da tradurre

- [x] Introduzione
- [x] Motivazione
- [x] L'algoritmo di confronto
- [x] Elementi di tipo diverso
- [x] Elementi DOM dello stesso tipo
- [ ] Elementi Componente dello stesso tipo
- [ ] Chiavi
- [ ] Compromessi

## Pre-commit
- [ ] Controllo finale del glossary e della guida di stile.
