### ISSUE TITLE
"Refactoring" => "rifattorizzazione" ?

### ISSUE THREAD

**Issue by deblasis** [reactjs/it.reactjs.org#9]
How shall we translate this?

As a seasoned engineer I would keep this in English but considering the audience and the fact that the Italian version seems to be used in the Academic world as well, maybe best to translate it? 
The first time I encountered it, I added a link to wikipedia (https://it.wikipedia.org/wiki/Refactoring). 
Thoughts?

**Comment by LucaBlackDragon** [comment]
For what it's worth, both terms are used seamlessly in my workplace, so I don't have strong opinions about this. Sticking with the Academy and providing a link to Wikipedia is better than good in my opinion (what I am actually thinking is *troppa grazia!* :D)

**Comment by deblasis** [comment]
Fair enough! 🤣
