### ISSUE TITLE
Translation for the page 'Additional Translations -> Community'

### ISSUE THREAD

**Issue by deblasis** [reactjs/it.reactjs.org#98]
# Please help us translating this page in Italian!
  
  **Aiutaci a tradurre questa pagina in Italiano!**

  You can find all the details about how to help here: https://github.com/reactjs/it.reactjs.org/issues/1
  
  ## GRAZIE! :smile:

**Comment by DennisBoanini** [comment]
Ciao @deblasis , posso prendermi in carico questo issue?
